/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeemanagement;

/**
 *
 * @author Admin PC
 */
import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;

public class AddEmployee extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
         conn=db.java_db();
 Toolkit toolkit = getToolkit();
  Dimension size = toolkit.getScreenSize();
  setLocation(size.width/2 - getWidth()/2, 
   size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_eid = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_con = new javax.swing.JTextField();
        txt_add = new javax.swing.JTextField();
        txt_dept = new javax.swing.JTextField();
        txt_deg = new javax.swing.JTextField();
        txt_doj = new javax.swing.JTextField();
        txt_bsal = new javax.swing.JTextField();
        txt_jtit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_gen = new javax.swing.JComboBox<>();
        txt_sta = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee ID:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 130, 100, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 170, 90, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 210, 80, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date of Birth:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 250, 100, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 290, 60, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 330, 70, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Address:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 370, 70, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Department:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(310, 130, 100, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Designation:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(310, 170, 100, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date of Joining:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(310, 210, 120, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Basic Salary:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(310, 250, 100, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Job Title:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(310, 330, 70, 17);
        jPanel1.add(txt_eid);
        txt_eid.setBounds(150, 120, 110, 30);
        jPanel1.add(txt_fname);
        txt_fname.setBounds(150, 160, 110, 30);
        jPanel1.add(txt_lname);
        txt_lname.setBounds(150, 200, 110, 30);

        txt_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dobActionPerformed(evt);
            }
        });
        jPanel1.add(txt_dob);
        txt_dob.setBounds(150, 240, 110, 30);

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel1.add(txt_email);
        txt_email.setBounds(150, 280, 110, 30);

        txt_con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_conActionPerformed(evt);
            }
        });
        jPanel1.add(txt_con);
        txt_con.setBounds(150, 320, 110, 30);
        jPanel1.add(txt_add);
        txt_add.setBounds(150, 360, 110, 30);

        txt_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deptActionPerformed(evt);
            }
        });
        jPanel1.add(txt_dept);
        txt_dept.setBounds(430, 120, 110, 30);

        txt_deg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_degActionPerformed(evt);
            }
        });
        jPanel1.add(txt_deg);
        txt_deg.setBounds(430, 160, 110, 30);
        jPanel1.add(txt_doj);
        txt_doj.setBounds(430, 200, 110, 30);

        txt_bsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bsalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_bsal);
        txt_bsal.setBounds(430, 240, 110, 30);

        txt_jtit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jtitActionPerformed(evt);
            }
        });
        jPanel1.add(txt_jtit);
        txt_jtit.setBounds(430, 320, 110, 30);

        jButton1.setText("ADD RECORD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 440, 99, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gender:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 290, 80, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(310, 370, 70, 17);

        txt_gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".........", "Male", "Female" }));
        txt_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_genActionPerformed(evt);
            }
        });
        jPanel1.add(txt_gen);
        txt_gen.setBounds(430, 280, 110, 30);

        txt_sta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "........", "Married", "Single" }));
        jPanel1.add(txt_sta);
        txt_sta.setBounds(430, 360, 110, 30);

        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(480, 440, 100, 50);

        jButton3.setText("BROWSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(630, 320, 120, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SEARCH EMPLOYEE:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(40, 60, 160, 17);

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(190, 50, 320, 30);

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(330, 440, 100, 50);

        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(180, 440, 100, 50);

        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(610, 10, 150, 40);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));

        img.setForeground(new java.awt.Color(255, 255, 255));
        img.setText("jLabel9");

        jDesktopPane1.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(630, 170, 121, 137);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employeemanagement/images/6.jpg"))); // NOI18N
        jLabel9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel9KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 810, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dobActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_conActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_conActionPerformed

    private void txt_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deptActionPerformed

    private void txt_degActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_degActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_degActionPerformed

    private void txt_bsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bsalActionPerformed

    private void txt_jtitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jtitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jtitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
                String sql ="insert into Staff_information " 
                        + "(first_name,last_name,Dob,Email,"
                        + "Telephone,Address,Department,"
                        + "Image,Salary,Gender,"
                        + "Designation,Status,job_title,Date_hired) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";

                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_fname.getText());
                pst.setString(2,txt_lname.getText());
                pst.setString(3,txt_dob.getText());
                pst.setString(4,txt_email.getText());
                pst.setString(5,txt_con.getText());
                pst.setString(6,txt_add.getText());
                pst.setString(7,txt_dept.getText());
                pst.setBytes(8,person_image);

                pst.setString(9,txt_bsal.getText());
                pst.setString(10, txt_gen.getSelectedItem().toString());
                pst.setString(11,txt_deg.getText());
                pst.setString(12,txt_sta.getSelectedItem().toString());
                pst.setString(13,txt_jtit.getText());
               
                pst.setString(14,txt_doj.getText());
                
               
                

                pst.execute();
                JOptionPane.showMessageDialog(null,"Data is saved successfully");

            }
            catch (Exception e)

            {
                JOptionPane.showMessageDialog(null,e);
            }
            try{
                
                String sq="select * from Staff_information where (id) NOT IN (select id from Users) ";
                pst=conn.prepareStatement(sq);
                rs=pst.executeQuery();
                
                while(rs.next())
                {
                    
                    String add1= rs.getString("id");
                    String add2= rs.getString("first_name");
                    String add3= rs.getString("Dob");
                    String result=add3.replace("/", "");
                    String add4= rs.getString("Department");
                    
                    
                    String sql="insert into Users(divison,username,password,id values('"+add4+"','"+add2+ "','"+result+"','"+add1+"')";
                    pst.execute();
                    JOptionPane.showMessageDialog(null,"User account has been created successfully: "+"Usernme: "+add2+ "Password: "+result);                }
                
            } catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
         }

        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_genActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_genActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        txt_eid.setText("");
        txt_fname.setText("");
        txt_lname.setText("");
        txt_con.setText("");
        txt_dob.setText("");
        txt_email.setText("");
        txt_add.setText("");
        txt_dept.setText("");
        
        txt_bsal.setText("");
        txt_jtit.setText("");
        txt_doj.setText("");
       
        txt_deg.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        filename =f.getAbsolutePath();
        ImageIcon imageIcon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(),img.getHeight(),Image.SCALE_DEFAULT));
        img.setIcon(imageIcon);
        try{
            File image=new File(filename);
            FileInputStream fix=new FileInputStream(image);
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            for(int number;(number=fix.read(buf))!=-1;)
            {
                bos.write(buf,0,number);
            }
            person_image=bos.toByteArray();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel9KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9KeyPressed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        try
        {
            String sql="select * from Staff_information where id=?";
            pst= conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            
            String add1=rs.getString("id");
            txt_eid.setText(add1);
            
            String add2=rs.getString("first_name");
            txt_fname.setText(add2);
            
            String add3=rs.getString("last_name");
            txt_lname.setText(add3);
            
            String add4=rs.getString("Dob");
            txt_dob.setText(add4);
            
            String add5=rs.getString("Email");
            txt_email.setText(add5);
            
            String add6=rs.getString("Telephone");
            txt_con.setText(add6);
            
            String add7=rs.getString("Address");
            txt_add.setText(add7);
            
            String add8=rs.getString("Department");
            txt_dept.setText(add8);
            
            String add9=rs.getString("Salary");
            txt_bsal.setText(add9);
            
            String add10=rs.getString("Status");
            txt_sta.setSelectedItem(add10);
            
            String add11=rs.getString("Date_hired");
            txt_doj.setText(add11);
            
            String add12=rs.getString("job_title");
            txt_jtit.setText(add12);
            
            String add13=rs.getString("Designation");
            txt_deg.setText(add13);
            
            byte[] image=rs.getBytes("Image");
            ImageIcon imageIcon =new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(img.getWidth(),img.getHeight() ,Image.SCALE_SMOOTH));
            img.setIcon(imageIcon);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        try{
            String sql="delete from Staff_information where id=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_eid.getText());
            pst.execute();
        JOptionPane.showMessageDialog(null,"record deleted");

            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }finally{
            try{
                rs.close();
                pst.close();
                
            }
            catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
            String value1=txt_fname.getText();
            String value2=txt_lname.getText();
            String value3=txt_dob.getText();
            String value4=txt_eid.getText();
            String value5=txt_email.getText();
            String value6=txt_con.getText();
            String value7=txt_add.getText();
            String value8=txt_dept.getText();
            String value9=txt_deg.getText();
           
            String value11=txt_jtit.getText();
            String value12=txt_sta.getSelectedItem().toString();
            String value13=txt_gen.getSelectedItem().toString();
            String value14=txt_doj.getText();
            
            String sql="update Staff_information set id="+value4+"first_name="+value1+"last_name="+value2+"Dob="+value3+"Email="+value5+"Telephone="+value6+
                    "Department="+value8+"Designation="+value9+"Address="+value7+"job_title="+value11+"Status="+value12+
                    "Gender="+value13+"Date_Hired="+value14+"";
             pst=conn.prepareStatement(sql);
             pst.execute();
             JOptionPane.showMessageDialog(null,"record deleted");
             
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"RECORD UPDATED");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
                MainMenu l = new MainMenu();
                    l.setVisible(true);
                    this.dispose();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_add;
    private javax.swing.JTextField txt_bsal;
    private javax.swing.JTextField txt_con;
    private javax.swing.JTextField txt_deg;
    private javax.swing.JTextField txt_dept;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_doj;
    private javax.swing.JTextField txt_eid;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JComboBox<String> txt_gen;
    private javax.swing.JTextField txt_jtit;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_search;
    private javax.swing.JComboBox<String> txt_sta;
    // End of variables declaration//GEN-END:variables
private ImageIcon format=null;
String filename=null;
byte[] person_image=null;
    
}
