/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeemanagement;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin PC
 */
public class UpdateSalary extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form UpdateSalary
     */
    public UpdateSalary() {
        initComponents();
        conn=db.java_db();
 Toolkit toolkit = getToolkit();
  Dimension size = toolkit.getScreenSize();
  setLocation(size.width/2 - getWidth()/2, 
   size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_bsal = new javax.swing.JTextField();
        txt_dept = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        r_per = new javax.swing.JRadioButton();
        r_amt = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_per = new javax.swing.JTextField();
        txt_amt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 160, 110, 17);

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(220, 60, 470, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee ID:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 60, 110, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 220, 100, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 280, 90, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date of Birth:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(420, 160, 100, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Basic Salary:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 220, 90, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Department:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 280, 90, 17);

        txt_id.setEditable(false);
        jPanel1.add(txt_id);
        txt_id.setBounds(220, 150, 150, 30);

        txt_fname.setEditable(false);
        jPanel1.add(txt_fname);
        txt_fname.setBounds(220, 210, 150, 30);

        txt_lname.setEditable(false);
        jPanel1.add(txt_lname);
        txt_lname.setBounds(220, 270, 150, 30);

        txt_dob.setEditable(false);
        jPanel1.add(txt_dob);
        txt_dob.setBounds(530, 150, 160, 30);

        txt_bsal.setEditable(false);
        jPanel1.add(txt_bsal);
        txt_bsal.setBounds(530, 210, 160, 30);

        txt_dept.setEditable(false);
        txt_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deptActionPerformed(evt);
            }
        });
        jPanel1.add(txt_dept);
        txt_dept.setBounds(530, 270, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Update Salary by :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(160, 350, 140, 17);

        r_per.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        r_per.setForeground(new java.awt.Color(255, 255, 255));
        r_per.setText("Percentage(%)");
        r_per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_perActionPerformed(evt);
            }
        });
        jPanel1.add(r_per);
        r_per.setBounds(320, 340, 140, 30);

        r_amt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        r_amt.setForeground(new java.awt.Color(255, 255, 255));
        r_amt.setText("Amount (Rs)");
        r_amt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_amtActionPerformed(evt);
            }
        });
        jPanel1.add(r_amt);
        r_amt.setBounds(490, 340, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Percentage:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(110, 410, 90, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Amount :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(420, 410, 90, 20);

        txt_per.setEditable(false);
        txt_per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_perActionPerformed(evt);
            }
        });
        jPanel1.add(txt_per);
        txt_per.setBounds(220, 400, 150, 30);

        txt_amt.setEditable(false);
        jPanel1.add(txt_amt);
        txt_amt.setBounds(530, 400, 160, 30);

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(650, 460, 130, 50);

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(683, 10, 90, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employeemanagement/images/6.jpg"))); // NOI18N
        jLabel11.setText("BACK");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 810, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deptActionPerformed

    private void txt_perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_perActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_perActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        
        try{
            String sql="select * from Staff_information where id=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            
            
            String add1=rs.getString("id");
            txt_id.setText(add1);
            
            String add2=rs.getString("first_name");
            txt_fname.setText(add2);
            
            String add3=rs.getString("last_name");
            txt_lname.setText(add3);
            
            String add4=rs.getString("Dob");
            txt_dob.setText(add4);
            
            String add5=rs.getString("Department");
            txt_dept.setText(add5);
            
            String add6=rs.getString("Salary");
            txt_bsal.setText(add6);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        if(r_per.isSelected()==true)
        {
        int sal=Integer.parseInt(txt_bsal.getText());
        int getp=Integer.parseInt(txt_per.getText());
        int cper=(sal/100)*getp+sal;
        String xP=String.valueOf(cper);
        txt_bsal.setText(xP);}
        
        
        else if(r_amt.isSelected()==true)
        {
            int sal=Integer.parseInt(txt_bsal.getText());
        int geta=Integer.parseInt(txt_amt.getText());
        int camt=geta+sal;
        String xA=String.valueOf(camt);
        txt_bsal.setText(xA);}
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        try{
            
            String value1=txt_id.getText();
            String value2=txt_bsal.getText();
            
            String sql="update Staff_information set id='"+value1+"',Salary='"+value2+"' where id='"+value1+"'  ";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Record Updated");
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void r_amtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_amtActionPerformed
        // TODO add your handling code here:
        r_amt.setSelected(true);
        r_per.setSelected(false);
        txt_amt.setEnabled(true);
        txt_per.setEnabled(false);
        txt_amt.setEditable(true);
        txt_amt.setText("");
    }//GEN-LAST:event_r_amtActionPerformed

    private void r_perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_perActionPerformed
        // TODO add your handling code here:
        
        r_per.setSelected(true);
        r_amt.setSelected(false);
        txt_per.setEnabled(true);
        txt_amt.setEnabled(false);
        txt_per.setEditable(true);
        txt_per.setText("");
    }//GEN-LAST:event_r_perActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MainMenu l = new MainMenu();
                    l.setVisible(true);
                    this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton r_amt;
    private javax.swing.JRadioButton r_per;
    private javax.swing.JTextField txt_amt;
    private javax.swing.JTextField txt_bsal;
    private javax.swing.JTextField txt_dept;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_per;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
